name: Basic-Workflow
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is the Test-job."
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - run: npm run js:lint
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is the Build-job."
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is the Deploy-job."
